User Journey Encarni 👽
JJ/KeMeVoi pull request #21
Opened 2023-10-05 07:35 UTC by carlotiii30

2023-10-05 07:46 UTC, pluque01 commented on user_journey-encarni.md
> +## User Journey Encarni
El título principal debe empezar con un #

2023-10-05 07:46 UTC, pluque01 commented on user_journey-encarni.md
> +Mi nombre es Encarni, soy jefa de proyectos en una importante empresa de Granada, todo un equipo depende de mi. Dos veces al año, en mayo y en septiembre, nos reúnen a todos los integrantes del equip
El linter avisa de que sobra un espacio al final, pero también va a dar fallo si no pones un límite de 80 caracteres por línea

2023-10-05 07:46 UTC, pluque01 commented on user_journey-encarni.md
> +Teniendo en cuenta que, sin un jefe de proyecto, el trabajo no puede avanzar, el equipo tiene que ponerse de acuerdo en la elección del periodo vacacional. Además, hay que cumplir ciertas condiciones
Aquí va a fallar por lo mismo, el límite de 80 caracteres por línea.

2023-10-05 08:19 UTC, puchy22 requested changes
Creo que sería conveniente añadir en más detalle qué es lo que hace Encarni desde que abre la aplicación hasta que la cierra.

2023-10-05 08:29 UTC, Enaraque commented
Ha fallado el workflow por el md de currante. Ya ha sido arreglado en el issue #24. 
Actualizad la rama para que no falle y asi se pueda hacer el merge 🤝

2023-10-05 10:34 UTC, JJ commented
> Ha fallado el workflow por el md de currante. Ya ha sido arreglado en el issue #24. Actualizad la rama para que no falle y asi se pueda hacer el merge 🤝

Lo puede hacer cualquiera con permiso de escritura :+1:

2023-10-26 06:55 UTC, javigp2002 reviewed
Está bien el user journey aunque quizás sea más HU que user journey a mi parecer. No obstante, miraría el problema que comento en el código.

2023-10-26 06:55 UTC, javigp2002 commented on user_journey-encarni.md
> +Cada equipo solicitará, en la aplicación, su periodo de preferencia, que podrá
¿Lo solicitá entonces para una persona o se pide para un equipo completo?

2023-10-26 07:39 UTC, javigp2002 approved these changes
:+1:

2023-10-26 08:01 UTC, puchy22 approved these changes

2023-10-26 08:01 UTC, puchy22 commented
:+1:

2023-10-26 10:07 UTC, merged