[IV-23-24] Documentacion
JJ/KeMeVoi pull request #29
Opened 2023-10-06 08:01 UTC by LuciaAnsino

Indice sobre el directorio doc #27 closes #27

# Plantilla de PR (título PR)

## Descripción

[Describe aquí de manera concisa cuál es el propósito
de esta solicitud de extracción.]

## Cambios realizados

* Cambio 1
* Cambio 2
* Cambio 3

## Issue relacionado

[Cierra el issue relacionado al completar el PR.
Por ejemplo, "Closes #X", siendo X el número del issue.]

## Capturas de pantalla (si es aplicable)

[Si los cambios incluyen modificaciones visuales, proporciona
capturas de pantalla antes y después, o describe cómo los
revisores pueden verificar visualmente los cambios.]

## Comprobación

Marca las siguientes casillas tras verificar que se han cumplido:

* [ ] He revisado y corregido cualquier error ortográfico o de formato.
* [ ] He probado los cambios y confirmado que funcionan como se espera.
* [ ] He seguido las pautas de estilo y formato del proyecto.

## Notas Adicionales

[Proporciona cualquier información adicional que consideres relevante
para esta solicitud de extracción, como posibles problemas conocidos
o consideraciones especiales.]

2023-10-06 08:54 UTC, JJ approved these changes
👏 Gracias

2023-10-18 08:02 UTC, Enaraque approved these changes

2023-10-18 08:18 UTC, JJ requested changes
Gracias por el trabajo realizado, hay quizás algunos pequeños problemas de formato que te agradecería que miraras.

2023-10-18 08:18 UTC, JJ commented on doc/README.md
> +![Gestión de vacaciones](./InformacionExtra.md)
La admiración antes del corchete corresponde a una imagen. Además, ¿has considerado la posibilidad de incluir un guión o asterisco para que se cree una lista?

2023-10-20 07:39 UTC, LuciaAnsino commented on doc/README.md
> +![Gestión de vacaciones](./InformacionExtra.md)
Resuelvo en el commit [3e21203](https://github.com/JJ/KeMeVoi/pull/29/commits/3e212038db2c59ca5a3cfb7d0ed32046527a38eb)

2023-10-20 07:52 UTC, JJ requested changes
Puedes siempre mirar en la pestaña de "Preview" para ver si efectivamente sale lo que quieres.

2023-10-20 07:52 UTC, JJ commented on doc/README.md
> +*[Gestión de vacaciones](./InformacionExtra.md)
Me temo que tienes que ponerlo separado con un espacio, si no lo interpreta como comienzo de cursivas.

2023-10-26 06:43 UTC, LuciaAnsino commented on doc/README.md
> +*[Gestión de vacaciones](./InformacionExtra.md)
Resuelvo en [e911029](https://github.com/JJ/KeMeVoi/pull/29/commits/e9110293388072b5214cd0c43514e9d49c48aaa6)

2023-10-26 06:54 UTC, Morad02 requested changes
El formato está bien, pero los enlaces no  funcionan.

2023-10-26 07:04 UTC, Enaraque commented
Los enlaces md no funcionan debido a que en el link recoge el nombre de la rama y es una rama de un fork que no existe en este repo. Una vez que se mergee a main funcionarán correctamente.

2023-10-26 07:07 UTC, Morad02 approved these changes

2023-10-26 07:08 UTC, javigp2002 approved these changes
:+1:

2023-10-26 07:56 UTC, JJ approved these changes
👍

2023-10-26 07:56 UTC, merged