👷 Añadido user journey de currante 🧐
JJ/KeMeVoi pull request #4
Opened 2023-09-28 07:48 UTC by Enaraque

Se ha añadido en el directorio `doc` el `readme` del journey de currante con la descripción de este.

2023-09-28 08:04 UTC, moshidev reviewed
Tal vez la edad no es relevante...

Por otra parte se podría dar el caso de que al rechazar la fecha de las vacaciones salgan otras fechas que no interesen a Miguel.

2023-09-28 08:06 UTC, PabloBarTo requested changes
En general veo que está bien solo que falta especificar la frecuencia con la que se usa.
¿Si vuelvo de las vacaciones puedo volver a utilizarlo?

2023-09-28 08:45 UTC, Enaraque commented
> En general veo que está bien solo que falta especificar la frecuencia con la que se usa. ¿Si vuelvo de las vacaciones puedo volver a utilizarlo?

@PabloBarTo  La frecuencia esta adjunta en el `readme` la cual es de `6 meses`

2023-09-28 12:41 UTC, JJ commented
Por favor, tratad de actualizar desde main para que incluya el workflow que comprueba markdown

2023-10-05 06:51 UTC, PabloBarTo approved these changes
Vale, entonces sí queda claro.

2023-10-05 06:52 UTC, manuelvico0102 approved these changes
Yo lo veo todo correcto

2023-10-05 06:58 UTC, merged