Información acerca de las personas
JJ/KeMeVoi pull request #5
Opened 2023-09-28 07:49 UTC by PabloBarTo

Usando vscode

2023-09-28 07:52 UTC, giorgiogiovanni requested changes

2023-09-28 07:52 UTC, giorgiogiovanni commented on doc/personas.md
> +**Jacinta**, mujer viuda de 35 años con un hijo de 4 años, trabaja desde hace tres año en instalaciones Barranco S.L. Junto con su compañera Antonia se encargan de la atención al cliente.
año -> años

2023-09-28 08:00 UTC, giorgiogiovanni approved these changes

2023-09-28 08:12 UTC, chelunike commented
Por el bien de clarificar la información, ¿como se llama el hijo? Además de incluir los apellidos para saber si mantiene los apellidos del padre o solo los de la madre.

2023-09-28 08:13 UTC, JJ requested changes
Cuando @marinajcs ha creado este fichero, ha usado la convención `persona-nombre.md` para el mismo. Es conveniente seguir esa convención.
Para cambiar de nombre, usa `git mv`, no simplemente `mv`

2023-09-28 12:17 UTC, JJ commented
Estoy mergeando main que ya tiene el linter de markdown; echadle un vistazo a los errores cuando lo pase.

2023-09-28 15:36 UTC, JJ commented
> Por el bien de clarificar la información, ¿como se llama el hijo? Además de incluir los apellidos para saber si mantiene los apellidos del padre o solo los de la madre.

¿De qué forma es eso relevante para la resolución del problema?

2023-09-29 08:56 UTC, marinajcs commented
Buenas, primero sería conveniente revisar los errores del test de formato Markdown:
- Separar en más de una línea los parráfos para que no superen el límite recomendado de 80 caracteres por línea
- Incluir al final del documento un único carácter de nueva línea (una línea en blanco al final del fichero)

La situación de conflicto entre Jacinta y su compañera a la hora de pedir vacaciones ayuda a entender mejor el problema a abordar. Como pequeña sugerencia, ya que se ha mencionado que es viuda, podría elaborarse un poco el contexto de cómo este hecho podría afectar a las fechas en las que puede organizar unas vacaciones con su hijo. Por ejemplo, en caso de no tener una cuidadora o familiar con quien dejarlo, ¿tiene que llevarlo todos los días a la escuela/guardería? ¿Esto le obliga a pedirse ciertas horas (en lugar de días enteros) de asuntos propios durante la semana?

2023-09-29 09:27 UTC, JJ commented
@marinajcs Como es una rama de este proyecto, cualquiera con permisos de escritura puede hacer cambios; específicamente, los de Markdown, que están señalados, como veis, en la pestaña “ficheros”

2023-09-29 15:34 UTC, JJ approved these changes
:clap:

2023-10-05 07:09 UTC, Christianlr commented
Buenas, @puchy22 y yo somos los dos nuevos revisores. Está todo bien, pero hemos observado que quizás vendría bien añadir alguna otra personal para conocer más al personal de la empresa. Por otro lado, para completar más el perfil o los perfiles que se describen, se podría añadir la formación/estudios o papel que desempeñan dentro de la empresa.

2023-10-05 07:24 UTC, PabloBarTo commented
@Christianlr @puchy22 Jacinta se encarga junto con Antonia de la atención al cliente.

2023-10-05 07:30 UTC, merged