Añadida persona Encarni
JJ/KeMeVoi pull request #7
Opened 2023-09-28 07:49 UTC by marinajcs

Se ha añadido un perfil de una empleada siguiendo la metodología de personas de Design Thinking.

2023-09-28 07:57 UTC, giorgiogiovanni commented on doc/persona-encarni.md
> +
Extra spaces. No es necesario dobles saltos de linea en una lista

2023-09-28 07:57 UTC, giorgiogiovanni commented on doc/persona-encarni.md
> +## Encarni, 42 años
Es recomendable separar los titulos "#" ..."##" con linea en blanco, aunque markdown lo pueda interpretar correctamente

2023-09-28 07:58 UTC, giorgiogiovanni requested changes

2023-09-28 07:58 UTC, giorgiogiovanni commented on doc/persona-encarni.md
> +# Metodología de personas
Revisar markdown

2023-09-28 08:07 UTC, Enaraque requested changes

2023-09-28 08:07 UTC, Enaraque commented on doc/persona-encarni.md
> +- Hobbies: Ir a la playa, surfear, viajar y realizar rutas
Estas características no son relevantes para el problema a resolver.

2023-09-28 08:12 UTC, danieeeld2 commented on doc/persona-encarni.md
> +- Hobbies: Ir a la playa, surfear, viajar y realizar rutas
Coincido con @Enaraque, creo que, a lo mejor, sería más interesante que hablase un poco sobre como quiere gestionar las vacaciones y ver después si eso es compatible con la información que han aportado los compañeros sobre como gestionan las empresas las vacaciones.

> Por ejemplo, le gustaría hacer coincidir sus vacaciones con la de su mujer e hijos para ir a Orlando en x fechas o algo así

No sé como lo ves tu @Enaraque

2023-10-04 07:16 UTC, giorgiogiovanni approved these changes

2023-10-04 15:09 UTC, danieeeld2 approved these changes

2023-10-04 15:26 UTC, JJ commented
Si @Enaraque cambia su revisión estamos listos.

2023-10-04 15:30 UTC, Enaraque approved these changes

2023-10-04 15:30 UTC, Enaraque commented
Listo @JJ

2023-10-04 15:32 UTC, merged